### ISSUE TITLE
list of languages

### ISSUE THREAD

**Issue by denics** [OVOSHatchery/ovos-stt-plugin-privox#1]
should not be the list of languages in a more generic library, like in ovos_utils?

**Comment by JarbasAl** [comment]
each plugin reports its supported languages, providing an example config for each

this info is then provided by ovos-plugin-manager in a global way depending on what plugins are installed, this is used for example in our setup skill

```python

from ovos_plugin_manager.stt import get_stt_lang_configs
from ovos_plugin_manager.tts import get_tts_lang_configs
```

**Comment by JarbasAl** [comment]
core can also be queried by bus api, this makes more sense for stuff like docker setups, since the process calling OPM methods may not be in same env as core itself

https://github.com/OpenVoiceOS/ovos-core/pull/220
